k

diff --git a/.github/workflows/aks-kubectl-apply.yml b/.github/workflows/aks-kubectl-apply.yml
--- a/.github/workflows/aks-kubectl-apply.yml
+++ b/.github/workflows/aks-kubectl-apply.yml
@@ -205,77 +205,72 @@ jobs:
             echo
           done
 
-      # - name: setup-ingress-controller
-      #   run: |
-      #     cd devops/helm-tools
-      #     chmod +x setup-ingress-controller.sh
-      #     ./setup-ingress-controller.sh
+      - name: setup-ingress-controller
+        run: |
+          cd devops/helm-tools
+          chmod +x setup-ingress-controller.sh
+          ./setup-ingress-controller.sh
 
-      # - name: Add grafana
-      #   run: |
-      #     cd devops/helm-tools
-      #     chmod +x grafana.sh
-      #     ./grafana.sh
+      - name: Add grafana
+        run: |
+          cd devops/helm-tools
+          chmod +x grafana.sh
+          ./grafana.sh
 
-      # - name: Apply ingresses
-      #   run: kubectl apply -f "$K8S_DIR/ingress" --recursive
+      - name: Apply ingresses
+        run: kubectl apply -f "$K8S_DIR/ingress" --recursive
 
-      # - name: Add prometheus
-      #   run: |
-      #     cd devops/helm-tools/prometheus
-      #     chmod +x prometheus.sh
-      #     ./prometheus.sh
+      - name: Add prometheus
+        run: |
+          cd devops/helm-tools/prometheus
+          chmod +x prometheus.sh
+          ./prometheus.sh
 
-      # - name: Add Loki (logs stack)
-      #   run: |
-      #     cd devops/helm-tools/loki
-      #     chmod +x loki.sh
-      #     ./loki.sh
+      - name: Add Loki (logs stack)
+        run: |
+          cd devops/helm-tools/loki
+          chmod +x loki.sh
+          ./loki.sh
 
-      # - name: Setup HTTPS certificates
-      #   run: |
-      #     cd devops/helm-tools
-      #     chmod +x setup-https.sh
-      #     ./setup-https.sh
+      - name: Setup HTTPS certificates
+        run: |
+          cd devops/helm-tools
+          chmod +x setup-https.sh
+          ./setup-https.sh
 
-      # - name: Wait for external IP for ingress controller
-      #   id: wait_for_ingress_ip
-      #   run: |
-      #     echo "Waiting for external IP for ingress-nginx-controller..."
-      #     for i in {1..30}; do
-      #       INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-      #       if [[ -n "$INGRESS_IP" ]]; then
-      #         echo "Ingress IP is ready: $INGRESS_IP"
-      #         echo "ingress_url=http://$INGRESS_IP" >> $GITHUB_OUTPUT
-      #         exit 0
-      #       fi
-      #       echo "Attempt $i: Ingress IP not yet assigned. Waiting 10s..."
-      #       sleep 10
-      #     done
-      #     echo "Failed to get ingress IP after waiting. Check 'kubectl get svc ingress-nginx-controller -n devops-ingress-nginx'"
-      #     exit 1
+      - name: Wait for external IP for ingress controller
+        id: wait_for_ingress_ip
+        run: |
+          echo "Waiting for external IP for ingress-nginx-controller..."
+          for i in {1..30}; do
+            INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            if [[ -n "$INGRESS_IP" ]]; then
+              echo "Ingress IP is ready: $INGRESS_IP"
+              echo "ingress_url=http://$INGRESS_IP" >> $GITHUB_OUTPUT
+              exit 0
+            fi
+            echo "Attempt $i: Ingress IP not yet assigned. Waiting 10s..."
+            sleep 10
+          done
+          echo "Failed to get ingress IP after waiting. Check 'kubectl get svc ingress-nginx-controller -n devops-ingress-nginx'"
+          exit 1
 
-      # - name: Add ingress IP to PostgreSQL firewall
-      #   run: |
-      #     INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
-      #     az postgres flexible-server firewall-rule create \
-      #       --resource-group $AKS_RG \
-      #       --name $PG_DB \
-      #       --rule-name allow-ingress-controller \
-      #       --start-ip-address $INGRESS_IP \
-      #       --end-ip-address $INGRESS_IP
+      - name: Add ingress IP to PostgreSQL firewall
+        run: |
+          INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          az postgres flexible-server firewall-rule create \
+            --resource-group $AKS_RG \
+            --name $PG_DB \
+            --rule-name allow-ingress-controller \
+            --start-ip-address $INGRESS_IP \
+            --end-ip-address $INGRESS_IP
 
       - name: Restart all pods in TARGET_NAMESPACE namespace
         run: |
           kubectl delete pod --all -n "$TARGET_NAMESPACE"
 
-      # - name: Output external URL
-      #   id: extract_url
-      #   run: |
-      #     echo "app_url=${{ steps.wait_for_ingress_ip.outputs.ingress_url }}" >> $GITHUB_OUTPUT
-      #     echo "App URL: ${{ steps.wait_for_ingress_ip.outputs.ingress_url }}"
-
       - name: Output external URL
         id: extract_url
         run: |
-          echo "app_url=123 >> $GITHUB_OUTPUT
+          echo "app_url=${{ steps.wait_for_ingress_ip.outputs.ingress_url }}" >> $GITHUB_OUTPUT
+          echo "App URL: ${{ steps.wait_for_ingress_ip.outputs.ingress_url }}"
