seperate

diff --git a/.github/workflows/aks-helmcharts.yaml b/.github/workflows/aks-helmcharts.yaml
--- a/.github/workflows/aks-helmcharts.yaml
+++ b/.github/workflows/aks-helmcharts.yaml
@@ -78,12 +78,40 @@ jobs:
           echo "AKS_RG=dev-zionet-learning-2025" >> $GITHUB_ENV
           echo "AKS_NAME=aks-cluster-dev" >> $GITHUB_ENV
 
+          # PG (per env name)
+          echo "PG_DB=${ENVIRONMENT_NAME}-pg-zionet-learning" >> $GITHUB_ENV
+          echo "PG_RG=${ENVIRONMENT_NAME}-zionet-learning-2025" >> $GITHUB_ENV
       - name: Get AKS credentials
         run: az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing
 
       - name: Ensure target namespace exists
         run: |
           kubectl create namespace "$TARGET_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
+
+      - name: Wait for external IP for ingress controller
+        run: |
+          echo "Waiting for external IP for ingress-nginx-controller..."
+          for i in {1..30}; do
+            INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            if [[ -n "$INGRESS_IP" ]]; then
+              echo "Ingress IP is ready: $INGRESS_IP"
+              echo "ingress_url=http://$INGRESS_IP" >> $GITHUB_OUTPUT
+              exit 0
+            fi
+            echo "Attempt $i: not ready. Sleeping 10s..."
+            sleep 10
+          done
+          echo "Failed to get ingress IP."; exit 1
+
+      - name: Add ingress IP to PostgreSQL firewall
+        run: |
+          INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          az postgres flexible-server firewall-rule create \
+            --resource-group $PG_RG \
+            --name $PG_DB \
+            --rule-name allow-ingress-controller \
+            --start-ip-address $INGRESS_IP \
+            --end-ip-address $INGRESS_IP
 
       - name: Helm template sanity (no Namespace objects)
         run: |
