Artur/602/create endpoint to get azure stt token (#630)
Co-authored-by: Benny <Benny902@gmail.com>

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -39,13 +39,22 @@ jobs:
       - name: Restore dependencies
         run: dotnet restore IntegrationTests.csproj
 
-      - name: Ensure correct appsettings.json
+      - name: Ensure jq is installed
         run: |
-          echo '{
-            "TestSettings": {
-              "ApiBaseUrl": "https://teachin.westeurope.cloudapp.azure.com/api/${{ inputs.api_stage }}/"
-            }
-          }' > appsettings.json
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y jq
+          else
+            echo "jq already installed"
+          fi
+
+      - name: Update ApiBaseUrl in appsettings.json
+        run: |
+          jq --arg url "https://teachin.westeurope.cloudapp.azure.com/api/${{ inputs.api_stage }}/" \
+            '.TestSettings.ApiBaseUrl = $url' appsettings.json > tmp.json && mv tmp.json appsettings.json
+        
 
       - name: Run integration tests
         run: dotnet test IntegrationTests.csproj --verbosity normal
